### ISSUE TITLE
2 Scrub roles got assigned by using the API

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1624] opened 2017-05-04 11:41 UTC
Version: openvstorage 2.8.2-1

2 Scrub roles got assigned by using the API.

**Comment by wimpers** [comment] 2017-05-29 14:14
@matthiasdeblock on the same disk? What does this break?

**Comment by kvanhijf** [comment] 2017-05-30 06:31
@wimpers : Scrubbing won't start. The scrubbing process doesn't expect this and doesn't know where to execute the actual scrubbing.
And i think it was on the same StorageRouter, not on the same disk/partition

**Comment by matthiasdeblock** [comment] 2017-05-30 08:09
This was indeed on the same storagerouter but on 2 different disks.

**Comment by saelbrec** [comment] 2017-05-30 08:45
In a setup where dedicated scrub nodes are used and can run multiple scrub jobs simultaneously it would make sense that we can use multiple devices(read: allow for multiple roles to be assigned and used).

**Comment by wimpers** [comment] 2017-06-01 13:16
This ticket is to fix the API issue.

Making sure the scrubber can work with 2 scrubdisks will be picked up in https://github.com/openvstorage/framework/issues/1624

**Comment by wimpers** [comment] 2017-06-06 12:27
@matthiasdeblock  can you reproduce this? What was the flow exactly? Did you call the API twice?

**Comment by JeffreyDevloo** [comment] 2017-06-06 16:20
This is still reproducable.

![selection_001](https://user-images.githubusercontent.com/17570109/26839934-c7f64cd2-4ae4-11e7-967e-bdbfa573d291.png)
The api has of course been called twice with different params to select a different disk.

**Comment by wimpers** [comment] 2017-06-07 07:08
So there is no real issue with the API. You just called it twice. In  https://github.com/openvstorage/framework/issues/1654 we will allow to set 2 or more scrub roles. Hence closing this ticket down.

**Comment by JeffreyDevloo** [comment] 2017-06-07 07:27
I do not agree with your statement.
Since the other implementation is currently not being worked, this should be blocked off as Kevin stated the scrubbing would not work.
Either close this down once #1654 has been addressed or this one.

**Closed as completed** 2017-06-07 07:30 UTC
Labels: type_bug, process_wontfix
