### ISSUE TITLE
ovs-workers log show invalid literal for int() with base 10 during urlparse of memcache servers

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1282] opened 2016-12-20 09:01 UTC
Environment: OVH
Only occurs on multiple host envs

```
Dec 20 09:14:39 ctrl-grav-04 celery[5694]: [2016-12-20 09:14:39,454: ERROR/MainProcess] pidbox command error: ValueError("invalid literal for int() with base 10: '11211;172.20.20.101'",)
Dec 20 09:14:39 ctrl-grav-04 celery[5694]: Traceback (most recent call last):
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/kombu/pidbox.py", line 105, in dispatch
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     reply = handle(method, kwdict(arguments))
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/kombu/pidbox.py", line 123, in handle_call
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     return self.handle(method, arguments)
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/kombu/pidbox.py", line 120, in handle
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     return self.handlers[method](self.state, **arguments)
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/celery/worker/control.py", line 377, in dump_conf
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     return jsonify(state.app.conf.table(with_defaults=with_defaults),
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/celery/app/utils.py", line 130, in table
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     self if with_defaults else self.without_defaults())
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/celery/app/utils.py", line 197, in filter_hidden_settings
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     return dict((k, maybe_censor(k, v)) for k, v in items(conf))
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/celery/app/utils.py", line 197, in <genexpr>
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     return dict((k, maybe_censor(k, v)) for k, v in items(conf))
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/celery/app/utils.py", line 193, in maybe_censor
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     return maybe_sanitize_url(value, mask=mask)
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 63, in maybe_sanitize_url
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     return sanitize_url(url, mask)
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 58, in sanitize_url
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     return as_url(*_parse_url(url), sanitize=True, mask=mask)
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 24, in _parse_url
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     return (scheme, unquote(parts.hostname or '') or None, parts.port,
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:   File "/usr/lib/python2.7/urlparse.py", line 113, in port
Dec 20 09:14:39 ctrl-grav-04 celery[5694]:     port = int(port, 10)
Dec 20 09:14:39 ctrl-grav-04 celery[5694]: ValueError: invalid literal for int() with base 10: '11211;172.20.20.101'
```

**Comment by khenderick** [comment] 2016-12-20 09:03
According to http://docs.celeryproject.org/en/latest/userguide/configuration.html#cache-backend-settings, the result backend should be set to sth like:

```cache+memcached://<ip>:<port>;<ip2>:<port2>/``` which can't be parsed by python's ```urlparse```. It's normal, because it's not a valid url, but the question is why this environment suddenly uses kombu > urlparse to parse the path.

This configuration isn't changed for a year, so why suddenly there's an environment that has issues with it.

**Comment by pploegaert** [comment] 2016-12-20 14:09
this can also be observed via celery flower in it's config tab
![screen shot 2016-12-20 at 15 09 48](https://cloud.githubusercontent.com/assets/8393135/21353464/6324aa4e-c6c6-11e6-925e-a24ec3a4783b.png)

e.g. http://127.0.0.1:5555/worker/celery@e187-1#tab-config

**Comment by khenderick** [comment] 2017-01-05 09:26
I never saw that on any other environment. @JeffreyDevloo, did you see it on any of your test envs?

**Comment by JeffreyDevloo** [comment] 2017-01-05 09:37
Did not encounter this message on:
- Personal test envir
- Nightly builds

Also I think that OVH is up for some maintenance/reinstall. With the loss of several nodes and the installation that went funky, I'd suggest putting some effort in into making it sane again (preferably by reinstalling)

**Comment by wimpers** [comment] 2017-01-05 09:39
After discussion with @khenderick , closing this ticket. Re-open if we can reproduce.

**Comment by jeroenmaelbrancke** [comment] 2017-05-30 15:40
Having the same problem on nuvolat setup.

```
May 30 11:28:55 NY1SRV0019 celery[30433]: [2017-05-30 11:28:55,474: ERROR/MainProcess] pidbox command error: ValueError("invalid literal for int() with base 10: '11211;172.17.16.25'",)
May 30 11:28:55 NY1SRV0019 celery[30433]: Traceback (most recent call last):
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/kombu/pidbox.py", line 105, in dispatch
May 30 11:28:55 NY1SRV0019 celery[30433]:     reply = handle(method, kwdict(arguments))
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/kombu/pidbox.py", line 123, in handle_call
May 30 11:28:55 NY1SRV0019 celery[30433]:     return self.handle(method, arguments)
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/kombu/pidbox.py", line 120, in handle
May 30 11:28:55 NY1SRV0019 celery[30433]:     return self.handlers[method](self.state, **arguments)
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/celery/worker/control.py", line 377, in dump_conf
May 30 11:28:55 NY1SRV0019 celery[30433]:     return jsonify(state.app.conf.table(with_defaults=with_defaults),
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/celery/app/utils.py", line 130, in table
May 30 11:28:55 NY1SRV0019 celery[30433]:     self if with_defaults else self.without_defaults())
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/celery/app/utils.py", line 197, in filter_hidden_settings
May 30 11:28:55 NY1SRV0019 celery[30433]:     return dict((k, maybe_censor(k, v)) for k, v in items(conf))
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/celery/app/utils.py", line 197, in <genexpr>
May 30 11:28:55 NY1SRV0019 celery[30433]:     return dict((k, maybe_censor(k, v)) for k, v in items(conf))
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/celery/app/utils.py", line 193, in maybe_censor
May 30 11:28:55 NY1SRV0019 celery[30433]:     return maybe_sanitize_url(value, mask=mask)
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 63, in maybe_sanitize_url
May 30 11:28:55 NY1SRV0019 celery[30433]:     return sanitize_url(url, mask)
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 58, in sanitize_url
May 30 11:28:55 NY1SRV0019 celery[30433]:     return as_url(*_parse_url(url), sanitize=True, mask=mask)
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 24, in _parse_url
May 30 11:28:55 NY1SRV0019 celery[30433]:     return (scheme, unquote(parts.hostname or '') or None, parts.port,
May 30 11:28:55 NY1SRV0019 celery[30433]:   File "/usr/lib/python2.7/urlparse.py", line 113, in port
May 30 11:28:55 NY1SRV0019 celery[30433]:     port = int(port, 10)
May 30 11:28:55 NY1SRV0019 celery[30433]: ValueError: invalid literal for int() with base 10: '11211;172.17.16.25'
```

**Comment by khenderick** [comment] 2017-05-30 15:53
Is it possible that you did install something via pip that somehow pulled different versions over?

**Comment by jeroenmaelbrancke** [comment] 2017-05-31 08:47
i was running celery flower, so maybe flower triggered these errors.

**Comment by JeffreyDevloo** [comment] 2017-05-31 09:29
Celery version is 3.1.23-5, identical to all our other environments that are running.
The error shown in the logs is identical to the one that is thrown when trying to fetch some info from the celery commandline:
```
root@e187-2:~# celery -A ovs.celery_run report
Traceback (most recent call last):
  File "/usr/bin/celery", line 26, in <module>
    load_entry_point("celery", "console_scripts", "celery")()
  File "/usr/lib/python2.7/dist-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/dist-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/dist-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python2.7/dist-packages/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 315, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 377, in handle_argv
    return self(*args, **options)
  File "/usr/lib/python2.7/dist-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/bin/celery.py", line 671, in run
    self.out(self.app.bugreport())
  File "/usr/lib/python2.7/dist-packages/celery/app/base.py", line 438, in bugreport
    return bugreport(self)
  File "/usr/lib/python2.7/dist-packages/celery/app/utils.py", line 225, in bugreport
    app.conf.CELERY_RESULT_BACKEND or 'disabled'),
  File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 63, in maybe_sanitize_url
    return sanitize_url(url, mask)
  File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 58, in sanitize_url
    return as_url(*_parse_url(url), sanitize=True, mask=mask)
  File "/usr/lib/python2.7/dist-packages/kombu/utils/url.py", line 24, in _parse_url
    return (scheme, unquote(parts.hostname or '') or None, parts.port,
  File "/usr/lib/python2.7/urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '11211;10.100.187.32'

```
It must have been an external tool (like flower) that was asking for this information aswell that caused the errors.

**Comment by JeffreyDevloo** [comment] 2017-06-13 14:50
This can be safely ignored. Occurs when fetching the information explicitly from rabbitmq when causes it to parse all URL through an URL parser which does not support comma separated lists.

**Closed as completed by JeffreyDevloo** 2017-06-13 14:50 UTC
