### ISSUE TITLE
vpool can be extended to node with no DB role.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#921] opened 2016-09-16 14:34 UTC
As seen in this error: 

```
2016-09-16 16:20:01 17100 +0200 - perf-grav-05 - 96030/140115547637568 - celery/celery.worker.job - 2226 - ERROR - Task ovs.storagerouter.add_vpool[b07e27d2-27f1-4bba-add5-a49af0332c89] raised unexpected: IndexError('list index out
 of range',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 487, in add_vpool
    db_available_size = partition_info[DiskPartition.ROLES.DB][0]['available']
IndexError: list index out of range
```

The GUI did not stop me from extending this vpool to the node in question without a DB disk

**Comment by wimpers** [comment] 2016-09-16 14:38
Duplicate of https://github.com/openvstorage/framework/issues/790 ?

**Comment by khenderick** [comment] 2016-09-16 14:51
Indeed a duplicate

**Closed as completed by khenderick** 2016-09-16 14:51 UTC
Labels: type_bug, process_duplicate
