### ISSUE TITLE
Add Snapshot and Set as vTemplate as possible actions for a vDisk

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#533] opened 2016-05-19 07:21 UTC
Add Snapshot and Set as vTemplate as possible actions for a vDisk. This is currently available for vMachines but not for vDisks.

**Comment by wimpers** [comment] 2016-06-20 14:56
@khenderick aren't you working on this one? I believe this is a duplicate?

**Comment by khenderick** [comment] 2016-06-20 15:01
This is indeed a duplicate of more recently created #629 because I just can't manage to find anything in this huge pile of tickets at various repositories. Adding to the confusion; it also wasn't linked to it's storycard.

**Closed as completed by khenderick** 2016-06-20 15:01 UTC
Labels: process_duplicate, type_feature
