### ISSUE TITLE
Remote support code should make use of the service manager

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework#1846] opened 2017-10-23 12:18 UTC
The remote support agent makes use of `check_output`, which can be used for bash code injection
Also the services being started and stopped are done by using systemctl commands, but the service manager should be used instead

**Comment by wimpers** [comment] 2017-12-14 10:41
Maybe the systemctl is on purpose as the systemctl works even in case the framework is down.  Maybe this was changed in the context of making the support agent always work.

**Comment by JeffreyDevloo** [comment] 2018-01-08 08:17
This is indeed intended behavior to keep the agent as robust as possible. Therefore closing this issue

**Closed as completed by JeffreyDevloo** 2018-01-08 08:17 UTC
Labels: type_bug, priority_minor
