### ISSUE TITLE
Partitioning fails on nvme devices

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#671] opened 2016-06-24 14:50 UTC
```
2016-06-24 16:39:40 14400 +0200 - allflash184 - 27800/139859220604736 - lib/scheduled tasks - 94 - INFO - Ensure single CHAINED mode - ID 1466779164_8adPfwzLfA - Task ovs.disk.sync_with_reality finished successfully
2016-06-24 16:39:40 15500 +0200 - allflash184 - 27800/139859220604736 - lib/storagerouter - 95 - DEBUG - Partition created
2016-06-24 16:39:40 15500 +0200 - allflash184 - 27800/139859220604736 - lib/storagerouter - 96 - DEBUG - Creating filesystem
2016-06-24 16:39:42 31100 +0200 - allflash184 - 27784/139859220604736 - celery/celery.worker.strategy - 90 - INFO - Received task: ovs.storagerouter.get_metadata[06ef18a5-ed42-4d42-bc19-481232c6e37d]
2016-06-24 16:39:42 31100 +0200 - allflash184 - 27784/139859220604736 - celery/celery.pool - 91 - DEBUG - TaskPool: Apply <function _fast_trace_task at 0x7f337ea346e0> (args:('ovs.storagerouter.get_metadata', '06ef18a5-ed42-4d42-bc19-481232c6e37d', ('8d79427f-0b98-494f-abd7-32f8d7801723',), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': ('8d79427f-0b98-494f-abd7-32f8d7801723',), 'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'sr.bpgIbSVzwJWKRaTk', u'exchange': u'generic'}, 'expires': None, u'hostname': 'celery@allflash184', 'task': 'ovs.storagerouter.get_metadata', 'callbacks': None, u'correlation_id': u'06ef18a5-ed42-4d42-bc19-481232c6e37d', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'c0146de5-8ea9-3c74-a36b-7f5a514f4269', 'id': '06ef18a5-ed42-4d42-bc19-481232c6e37d', u'headers': {}}) kwargs:{})
2016-06-24 16:39:42 31200 +0200 - allflash184 - 27784/139859220604736 - celery/celery.worker.job - 92 - DEBUG - Task accepted: ovs.storagerouter.get_metadata[06ef18a5-ed42-4d42-bc19-481232c6e37d] pid:27801
2016-06-24 16:39:42 74700 +0200 - allflash184 - 27784/139859220604736 - celery/celery.worker.job - 93 - INFO - Task ovs.storagerouter.get_metadata[06ef18a5-ed42-4d42-bc19-481232c6e37d] succeeded in 0.434760452015s: {'writecache_size': 0, 'mountpoints': [u'/home', u'/mnt/nvme'], 'scrub_available': True, 'shared_size': 0, 'ipaddresses':...
2016-06-24 16:39:43 42700 +0200 - allflash184 - 27784/139859220604736 - celery/celery.worker.job - 94 - ERROR - Task ovs.storagerouter.configure_disk[17af1a98-036c-42e6-bd2a-c8225e1d0f43] raised unexpected: CalledProcessError()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 297, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1964, in configure_disk
    rem.DiskTools.make_fs(partition.path)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
Exception
```

**Comment by wimpers** [comment] 2016-06-27 11:45
Duplicate of 644 ?

**Comment by pploegaert** [comment] 2016-06-27 11:54
No, this is triggered in storagerouters -> disks, fixing this will not solve #644 either
While #644 is on backend detail level ...

**Comment by wimpers** [comment] 2016-09-05 12:13
@pploegaert  can you validate if still an issue

**Comment by kinvaris** [comment] 2016-11-03 09:10
PASSED: validated in https://github.com/openvstorage/framework/issues/1062

**Closed as completed by kinvaris** 2016-11-03 09:10 UTC
Labels: type_bug, priority_critical
