### ISSUE TITLE
5 minutes to load the backend page

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1650] opened 2017-05-29 08:16 UTC
On Nuvolat it takes 5 minutes to load one backend (asd/presets).

Please have a look at 172.17.16.22.

**Comment by wimpers** [comment] 2017-05-29 13:47
When did you first notice this? # backends? # ASDs?

**Comment by jeroenmaelbrancke** [comment] 2017-05-30 07:45
On the nuvolat setup with +500 asds spread around 8 backends.

**Comment by khenderick** [comment] 2017-06-01 08:14
The issue is more about the 60+ storagenodes in combination with near real-time status fields.

**Comment by khenderick** [comment] 2017-06-01 08:17
Fixed by
* #1652, packaged in openvstorage-2.9.5
* openvstorage/framework-alba-plugin#412, packaged in openvstorage-backend-1.9.1

**Comment by khenderick** [comment] 2017-06-06 14:04
Let's leave it on milestone `H` anyway, I have no idea when this "urgent" fix has to be released.

**Closed as completed** 2017-08-10 08:13 UTC
Labels: priority_critical, type_enhancement
