### ISSUE TITLE
View Not Found. Searched for "viewmodels/shell" via path "text!viewmodels/shell.html".

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#816] opened 2016-08-12 15:07 UTC
When first going to the GUI, it sometimes show "View Not Found. Searched for "viewmodels/shell" via path "text!viewmodels/shell.html"." a refresh fixes it.
![2016-08-12_17-05-04](https://cloud.githubusercontent.com/assets/8392927/17626797/1874e554-60af-11e6-92b2-e4d972386ed8.png)

**Comment by JeffreyDevloo** [comment] 2016-08-19 11:14
You can also reproduce this error by going into the menu and click on 'API' and then go back with the 'back' arrow.
If you can't reproduce it on a certain node, repeat the same steps on a different node.
Edit: I get the most success rate when I start from the vTemplates page.

**Comment by khenderick** [comment] 2016-09-08 08:57
Something I noticed recently is that with a newer browser it tends to be harder to reproduce. With Chrome 52 I could reproduce it every now and then, while I could never reproduce it with 54.

**Comment by wimpers** [comment] 2016-10-03 13:28
Haven't seen this one for a while now.

**Comment by pploegaert** [comment] 2016-10-03 13:30
It's still an issue... I notice this a few times a week at least ...

**Comment by wimpers** [comment] 2016-10-03 13:30
Which version of Chrome?

**Comment by pploegaert** [comment] 2016-10-03 13:31
53.0.2785.116 (64-bit)

**Comment by khenderick** [comment] 2016-10-11 12:11
Fixed by #1017, packaged in openvstorage-2.7.4-rev.4115.c0dda6a

**Comment by JeffreyDevloo** [comment] 2016-10-17 12:53
### Steps

### Steps
- Installed latest packages
- Installed cluster
- Added roles to disks
- Added backend
- Initialized disks and claimed asds
- Added usable preset
- Added vpool

Cluster has been setup.
Reproduction for the viewmodel error (as I reported above):
Did the reproduction tactic (that guaranteed the error) 5x for every node.

### Output

All pages loaded without a single viewmodel error.

### Test result

Test passed.

### Packages
- openvstorage                       2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage
- openvstorage-backend               1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.4-rev.766.0d9f30e-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                   1.6.4-rev.388.1f4375d-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps               2.7.4-rev.4159.0707c77-1                                 amd64        openvStorage Web Applications

**Closed as completed by JeffreyDevloo** 2016-10-17 12:53 UTC
Labels: type_bug, priority_normal
