### ISSUE TITLE
Store the creation date of a vdisk

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1936] opened 2018-01-18 14:58 UTC
It might come in handy to store the creation date of a vdisk. If the logs are rotated, you are unable to know when the volume got created.

**Comment by wimpers** [comment] 2018-01-18 15:01
Duplicate of https://github.com/openvstorage/framework/issues/1764. Re-open if you would disagree.

**Closed as completed by wimpers** 2018-01-18 15:01 UTC
Labels: process_duplicate
