### ISSUE TITLE
vPool creation failed: `Please check the logs for more information` but no logging

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1051] opened 2016-10-17 16:39 UTC
When performing a shrink of a vpool, I got this error in `ovs-workers`:

```
2016-10-17 18:31:34 96600 +0200 - ovs-node3 - 12833/139899174090560 - celery/celery.worker.job - 53553 - ERROR - Task ovs.storagerouter.remove_storagedriver[f1ca25a4-860
7-42e3-9dea-2f21a0642561] raised unexpected: RuntimeError('1 or more errors occurred while trying to remove the storage driver. Please check the logs for more informatio
n',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1280, in remove_storagedriver
    raise RuntimeError('1 or more errors occurred while trying to remove the storage driver. Please check the logs for more information')
RuntimeError: 1 or more errors occurred while trying to remove the storage driver. Please check the logs for more information
```

When trying to search the logs as said in the code: https://github.com/openvstorage/framework/blob/6f02d53ebd8a472840fca68e57f3303f16d7c510/ovs/lib/storagerouter.py#L70

We cannot find anything in `/var/log/ovs/lib.log`

**Comment by khenderick** [comment] 2016-10-19 07:54
That's most likely because we log to stdout by default, which causes the logs to be collected by upstart in `/var/log/upstart/ovs-*`. So `the logs` we refer to, is in that case the logs in `/var/log/upstart/ovs-*`.

The log location `/var/log/ovs/*` is only used as a fallback when the ovs shell (and ovs \* commands) is (are) used (since otherwise log entries would flood the shell's output if logged to stdout).

**Comment by JeffreyDevloo** [comment] 2016-11-22 15:40
### Information
The ticket is first and foremost hard to reproduce as an error occurred that was not known and no information was given about.
Second of all the ticket did not explore all possible options for logging locations.
Closing this one and waiting for more input in case it might have happened again.

**Closed as completed by JeffreyDevloo** 2016-11-22 15:40 UTC
Labels: type_bug
