### ISSUE TITLE
missing package openvstorage-sdm on a controller node

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1635] opened 2017-05-10 09:28 UTC
When installing a controller node with openvstorage-backend (not openvstorage-hc) the refresh_package_information tasks error with missing package openvstorage-sdm...
This is normal because we are not using this node as a hc node.

packages:
```
openvstorage                         2.9.2-1                                    amd64        openvStorage
openvstorage-backend                 1.8.1-1                                    amd64        openvStorage Backend plugin
openvstorage-backend-core            1.8.1-1                                    amd64        openvStorage Backend plugin core
openvstorage-backend-webapps         1.8.1-1                                    amd64        openvStorage Backend plugin Web Applications
openvstorage-core                    2.9.2-1                                    amd64        openvStorage core
openvstorage-webapps                 2.9.2-1                                    amd64        openvStorage Web Applications

```
```
May 10 11:10:13 stor-221-3 celery[13856]: 2017-05-10 11:10:13 71200 +0200 - stor-221-3 - 13856/140065605535488 - celery/celery.worker.job - 4305 - ERROR - Task ovs.generic.refresh_package_information[044bde4c-af92-4c1d-a883-313b79b5c6f5] raised unexpected: Exception(' - 10.100.199.230: Missing non-installed package: openvstorage-sdm',)
May 10 11:10:13 stor-221-3 celery[13856]: Traceback (most recent call last):
May 10 11:10:13 stor-221-3 celery[13856]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
May 10 11:10:13 stor-221-3 celery[13856]:     R = retval = fun(*args, **kwargs)
May 10 11:10:13 stor-221-3 celery[13856]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
May 10 11:10:13 stor-221-3 celery[13856]:     return self.run(*args, **kwargs)
May 10 11:10:13 stor-221-3 celery[13856]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 341, in new_function
May 10 11:10:13 stor-221-3 celery[13856]:     output = function(*args, **kwargs)
May 10 11:10:13 stor-221-3 celery[13856]:   File "/opt/OpenvStorage/ovs/lib/generic.py", line 621, in refresh_package_information
May 10 11:10:13 stor-221-3 celery[13856]:     raise Exception(' - {0}'.format('\n - '.join(errors)))
May 10 11:10:13 stor-221-3 celery[13856]: Exception:  - 10.100.199.230: Missing non-installed package: openvstorage-sdm

```

**Comment by wimpers** [comment] 2017-05-29 14:01
@jeroenmaelbrancke  what is failing because of this? HC?

**Comment by kvanhijf** [comment] 2017-05-30 06:34
@wimpers : The only thing that will fail because of this is retrieving the latest update information (and most likely the actual update too)

**Comment by saelbrec** [comment] 2017-05-30 07:31
Next to fixing we need to document the steps/patches required to be able to execute an update.
@wimpers, I think we want to have this fixed in the upcoming update.

**Comment by kvanhijf** [comment] 2017-06-07 07:53
@matthiasdeblock just ran into this issue while updating. So confirmed that it breaks the update

**Comment by matthiasdeblock** [comment] 2017-06-09 12:33
@kvanhijf when upgrading nuvolat I first installed sdm to make sure the update did work.

**Comment by khenderick** [comment] 2017-06-09 12:34
@kvanhijf was wrong _again_.

**Comment by khenderick** [comment] 2017-06-09 12:43
Fixed by openvstorage/framework-alba-plugin#417, packaged in openvstorage-backend-1.9.2-dev.1497012086.ac40c70

**Comment by khenderick** [comment] 2017-06-09 13:39
@saelbrec, please note that this is a fix in the update logic, so this will only be resolved _after_ this version is installed so when updating to the version _after_ this one.

**Comment by JeffreyDevloo** [comment] 2017-07-11 14:42
Packaged in openvstorage-backend_1.9.2-1_amd64.deb

**Closed as completed** 2017-08-10 08:13 UTC
Labels: type_bug
