### ISSUE TITLE
Clone vDisk fails

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework#717] opened 2016-07-13 07:53 UTC
Clone vDisk fails on the OVH setup (probably an issue with the create snapshot step in the clone flow)

**Comment by kvanhijf** [comment] 2016-07-13 08:37
Failed to reproduce this issue

Successfully cloned an empty disk with a new snapshot on same storagerouter
Successfully cloned an empty disk with an existing snapshot on same storagerouter
Successfully cloned an empty disk with a new snapshot on different storagerouter
Successfully cloned an empty disk with an existing snapshot on different storagerouter

Started cloning a disk with 250GB of stored data and could see write actions in the volumedriver logging on the storagerouter hosting the vdisk. Also noticed read actions in the volumedriver logging on the storagerouter i was cloning too
Cloning process still ongoing

As discussed with @redlicha , this is expected behaviour
For demo purposes, its better to clone a vdisk with a small amount of backend data and a low amount of tlogs.

For now i was unable to determine the rootcause why the snapshot creation was failing yesterday evening. Will further investigate after having improved the vpool wizard backend loading

**Comment by khenderick** [comment] 2016-07-14 16:05
As a general remark here: When creating a clone, the snapshot from which to clone (can be an existing or a new one) needs to be synced to the backend. If e.g. a new volume of tens of gigabytes is created and immediately after that cloned, it might take too long for the snapshot to be synced to the backend as the framework currently only waits for about 5 minutes.

We might want to tweak this timeout. Any suggestions, @wimpers?

**Comment by wimpers** [comment] 2016-07-14 20:51
If you hit that timeout I assume you see this in the logs? Just to be clear we didn't even see the snapshot call coming through.

**Comment by wimpers** [comment] 2016-07-14 20:52
I also can't reproduce it alas :(

**Comment by khenderick** [comment] 2016-07-15 04:14
It will be in the logs. More specific it should be in `/var/log/upstart/ovs-workers.log` on one of the nodes. But unfortunately, I didn't receive any logs from any of the occurrences except that _it didn't work_.

**Comment by wimpers** [comment] 2016-07-15 06:26
That is it, there was nothing in the logs. I'll close this one as we can't reproduce.

**Comment by pploegaert** [comment] 2016-07-15 06:42
Note that India reported the same issue yesterday - during their kernsafe demo preparations

**Comment by wimpers** [comment] 2016-07-15 06:44
@pploegaert please try to find the exact steps in order to reproduce. Assigning to you

**Comment by khenderick** [comment] 2016-07-15 07:02
@pploegaert, basically you want to search in the `ovs-workers.log` for `Snapshot XYZ of volume ABC still not synced to backend, not waiting any longer`. This indicates a snapshot could not be synced to backend in 5 minutes. If this is the case, please report size of volume, how many snapshots were already taken and information of the backend to be able to discuss whether we need to increase the timeout or not.

If anything else goes wrong, then the location of the logs may vary, as will the error message.

**Comment by JeffreyDevloo** [comment] 2016-08-26 13:39
Will try to reproduce by throttling the disk on which the asds are configured.

**Comment by khenderick** [comment] 2016-08-26 13:44
@JeffreyDevloo, to be clear on this one; if you can indeed reproduce the issue (and see the expected error) like we discussed, the only thing we can do is increase the timeout. So in that case you might try to figure out what would be a reasonable timeout to wait for a snapshot to sync to the backend (currently it's 5 minutes). 

/cc @wimpers for timeout input.

**Comment by JeffreyDevloo** [comment] 2016-11-03 16:04
### Feedback

My first iteration to test was using cgroups. These groups allow you to set policies on system resources.
I have used the following code to throttle all ovs processes:

```
#!/bin/bash
CONFIG_BLK_CGROUP=y
CONFIG_CFQ_GROUP_IOSCHED=y

testdirname=limit1k
io_in_bytes=1024

mount -t tmpfs cgroup_root /sys/fs/cgroup
mkdir -p /sys/fs/cgroup/blkio
mount -t cgroup -o blkio none /sys/fs/cgroup/blkio
mkdir -p /sys/fs/cgroup/blkio/$testdirname/
# Clear files
echo "" >> /sys/fs/cgroup/blkio/$testdirname/tasks
echo "" >> /sys/fs/cgroup/blkio/$testdirname/blkio.throttle.write_bps_device
# All running ovs IDS.
plist=$(initctl list | grep ovs | sort | cut -d ' ' -f 4)
for p in ${plist}
do
 echo ${p} > /sys/fs/cgroup/blkio/$testdirname/tasks
done

echo "8:0  $io_in_bytes" > /sys/fs/cgroup/blkio/$testdirname/blkio.throttle.write_bps_device
echo "8:16 $io_in_bytes" > /sys/fs/cgroup/blkio/$testdirname/blkio.throttle.write_bps_device
echo "8:32 $io_in_bytes" > /sys/fs/cgroup/blkio/$testdirname/blkio.throttle.write_bps_device
```

However, running a fio has showed me that this throttling did not work. I have insufficient knowledge about cgroups to spot where I went wrong.

My second approach is virtualizing an environment and limiting the VMs resources.
For this I have created a script to limit my IO of my vms:

```
import subprocess


class LimitDiskIo(object):

    def __init__(self):
        """
        Init
        """

    @staticmethod
    def limit_io(domain_name, devices=None, write_limit=None, read_limit=None):
        """
        Will limit the io the the provided values for a domain

        :param domain_name: name of the vm
        :type domain_name: str
        :param devices: list of all devices to limit eg [vda, sda]
        :type devices: list
        :param write_limit: write/s limit in bytes
        :type write_limit: int
        :param read_limit: read/s limit in bytes
        :type read_limit: int
        :return:
        """

        if domain_name not in LimitDiskIo._get_vm_list()['running']:
            raise ValueError('Domain name is incorrect')
        if domain_name in LimitDiskIo._get_vm_list()['shut off']:
            raise ValueError('Domain is currently not running.')
        if write_limit is None:
            write_limit = 1024*1024
        if read_limit is None:
            read_limit = 1024*1024
        if devices is None:
            devices = []
        # Map devices
        mapped_devices = LimitDiskIo._list_devices(domain_name)
        for key in devices:
            if key not in mapped_devices.keys():
                mapped_devices.pop(key, None)
        # Execute limit command
        for device in mapped_devices.keys():
            cmd = "virsh blkdeviotune {0} {1} --read-bytes-sec {2} --write-bytes-sec {3}  --current".format(domain_name, device, read_limit, write_limit)
            subprocess.check_output(cmd, shell=True)

    @staticmethod
    def is_limited(domain_name, devices=None):
        """
        Check if a device has been limited

        :param domain_name: name of the vm
        :type domain_name: str
        :param devices: list of all devices to limit eg [vda, sda]
        :type devices: list
        :return: a dict containing the names of devices that are throttled and on what they are throttled
        :rtype: dict of dicts
        """
        if devices is None:
            devices = []

        # Map devices
        mapped_devices = LimitDiskIo._list_devices(domain_name)
        for key in devices:
            if key not in mapped_devices.keys():
                mapped_devices.pop(key, None)

        limited = {}
        for device in mapped_devices.keys():
            limited_device = {}
            cmd = "virsh blkdeviotune {0} {1}".format(domain_name, device)
            output = subprocess.check_output(cmd, shell=True)
            for line in output.splitlines():
                if len(line.split()) != 0:
                    current_io = line.split()[0][:-1]
                    current_io_value = line.split()[1]
                    if current_io_value == ":":
                        current_io_value = line.split()[2]
                    if current_io_value != '0':
                        limited_device[current_io] = current_io_value
            limited[device] = limited_device
        return limited

    @staticmethod
    def _get_vm_list():
        querying_status = ['running', 'shut off']
        all_vms = {}
        for status in querying_status:
            all_vms[status] = []
            cmd = "virsh list --all | grep '{0}' | awk '{{ print $2 }}'".format(status)
            output = subprocess.check_output(cmd, shell=True)
            for domain_name in output.splitlines():
                all_vms[status].append(domain_name)
        return all_vms

    @staticmethod
    def _list_devices(domain):
        cmd = "virsh domblklist {0} | grep / ".format(domain)
        output = subprocess.check_output(cmd, shell=True)
        devices = {}
        for line in output.splitlines():
            devices[line.split()[0]] = line.split()[1]
        return devices
```

This approach seems to give the wanted results.
I will post back with more input.

**Comment by wimpers** [comment] 2016-11-04 08:03
Removing milestone and setting to state_question awaiting @JeffreyDevloo 's input

**Comment by JeffreyDevloo** [comment] 2016-11-04 08:51
### Information

Afther throttling the disks to 2.2mb/s and cloning a volume of 4.55GB after I queued the snapshot I have run into the expected 'Snapshot myshapshot01 of volume myvdisk01 still not synced to backend, not waiting any longer'

### Steps
- Added a new vdisk mydisk01
- Wrote 5GB of data using fio to the volume
- Started throttling all backend disks to 2.2mb/s
- Manually made a snapshot mysnapshot01
- Started cloning myvdisk01 from snapshot mysnapshot01

### Conclusion

After extensively trying to reproduce the error proposed by Kenneth, I conclude that this is a possible issue that can come up with bigger volumes. The fix is increasing the timeout however I cannot propose a decent timeout as my setup was doomed to fail in all cases.

I will close this ticket and if a similar issue with cloning comes up, we must have more logs to truly know that was going on because this case was feeling in the dark.

**Closed as completed by JeffreyDevloo** 2016-11-04 08:51 UTC
Labels: type_bug, process_wontfix, priority_critical
