### ISSUE TITLE
ArakoonClient does not report new master after re-election but still reports old one

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/framework#1617] opened 2017-04-27 16:14 UTC
I found this whilst fiddling with the arakoon support tools part. The ArakoonClient does not report the current/new master after a re-election. The situation at the start:

In [68]: arakoonclient.whoMaster()
Out[68]: 'Zuaq8gS2erJqNM0N'

2017-04-27 17:59:41 026184 +0200 - ovs-node03-1604 - 6961/0000 - arakoon - 1467 - info - Zuaq8gS2erJqNM0N is master

After using the --drop-master functionality of arakoon, a new master is elected:

2017-04-27 18:04:44 215042 +0200 - ovs-node03-1604 - 6961/0000 - arakoon - 1494 - info - connection=10.100.199.183:client_service_41 DROP_MASTER
2017-04-27 18:05:43 185928 +0200 - ovs-node03-1604 - 6961/0000 - arakoon - 1564 - info - wRvFcy0LkY3TOHXD is master

Checking again with the ArakoonClient:

In [72]: arakoonclient.whoMaster()
Out[72]: 'Zuaq8gS2erJqNM0N'

In [73]: arakoonclient = ArakoonClient(conf)

In [74]: arakoonclient.whoMaster()
Out[74]: 'wRvFcy0LkY3TOHXD'

Only after re-creating the ArakoonClient, I was able to retrieve the current master. I'm assuming this is not expected behavior or am I missing something?

**Comment by kvanhijf** [comment] 2017-04-28 06:49
```
def whoMaster(self):
    self._client.determine_master()
    return self._client.master_id

def determine_master(self):
    node_ids = []

    if self.master_id is None:
        node_ids = self._config.getNodes().keys()
        random.shuffle(node_ids)
        ...
```

In above snippet you can see that `determine_master` is only executed `if self.master_id is None`. So once you've determined the master, the same client instance will always return the same `whoMaster` output.
@toolslive , @khenderick : Don't know if this is by design or a bug

**Comment by khenderick** [comment] 2017-04-28 07:09
After some discussions with @kvanhijf, he'd love to get to know pyrakoon a bit better.

**Comment by kvanhijf** [comment] 2017-04-28 07:12
@khenderick , i think you misunderstood me, assigning to @domsj

**Comment by toolslive** [comment] 2017-04-28 07:52
It can happen a client thinks the wrong node is master. 
The next call that uses that assumed master node and needs it to be master will fail on server side, 
and that exception should be picked up by the client which should then correct its inner state. 
Thus far, the reported behaviour does not look like a bug.

https://github.com/openvstorage/pyrakoon/blob/0adf7aecef833a0fd85e6529d1a8d6188d1fecaa/pyrakoon/compat.py#L1106

**Comment by toolslive** [comment] 2017-05-02 09:52
note that `master_id` is a public attribute, and can be set to `None` prior to a `whoMaster()` call

**Comment by jtorreke** [comment] 2017-05-04 08:02
Aha! This is useful information. Thanks, Romain!
I'll try to test this somewhere today.

**Comment by wimpers** [comment] 2017-05-05 11:58
@jtorreke  please close if validated

**Comment by jtorreke** [comment] 2017-05-05 12:40
For completeness' sake: self._client.master_id = None
But it seems to work. Thanks Romain!

**Closed as completed** 2017-05-05 12:40 UTC
Labels: process_wontfix
