### ISSUE TITLE
Loading information from storage routers takes a long time, except when refreshing the page.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#638] opened 2016-06-20 13:17 UTC
When looking at the information on a storage driver, or when one wants to change the `domains` &/or `failure domains` of that storagedriver. It takes a long time to load the information except when just hitting `F5` to refresh the page.

Bug: https://s31.postimg.org/ath5dzlx7/bug_ovs_1_sr.png

When hitting `F5`, it successfully loads: https://s32.postimg.org/4vz180m45/bug_ovs_2_sr.png

**Comment by khenderick** [comment] 2016-07-26 08:36
Fixed by #742

**Comment by JeffreyDevloo** [comment] 2016-08-23 11:09
### Steps
- 3 node setup
- Added backend, vpool
- Added a domain 'vm-vpool-test'
- Added all nodes and backend to domain
- Checked if the domain would load when clicking on the entries in the lists

### Output

All domain information loaded instantaneously.

### Test result

Could not reproduce the issue. The information seems to load in an instant.
Closing.

### Package information
- openvstorage                       2.7.2-rev.3859.42b3488-1   amd64        openvStorage
- openvstorage-backend               1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.32.948a8c1-1 amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.2-rev.3859.42b3488-1   amd64        openvStorage core 
- openvstorage-hc                    1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.117.3212ea9-1    amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.2-rev.330.f06c8de-1    amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.2-rev.980.0dbc80f-1    amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.2-rev.3859.42b3488-1   amd64        openvStorage Web Applications

**Closed as completed by JeffreyDevloo** 2016-08-23 11:09 UTC
Labels: type_bug, priority_critical
