### ISSUE TITLE
Add vpool wizard skips step when Fragment cache is marked as disabled and user clicks on previous

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#677] opened 2016-06-28 11:40 UTC
Scenario:
Add vpool wizard
- fill out name + choose local alba backend
- Fragment Cache: No caching
- click Next
- click Previous
  -> Wizard ends up in first screen io Fragment cache screen

**Comment by khenderick** [comment] 2016-07-25 09:48
Can't reproduce this anymore, so it must have been resolved by #729

**Comment by deepshirsath** [comment] 2016-08-11 15:23
Re-tested and **PASSED** on **_Open vStorage: 2.7.1-fargo.2-1_**

**Steps performed :-** 
- Navigated to add new vPool wizard & filled out vPool name + selected local alba backend

![add-new-pool](https://cloud.githubusercontent.com/assets/14201912/17593883/03d7d48a-6005-11e6-81c3-0200fc3d2975.PNG)
- Next screen, selected Fragment Cache: **No caching**

![frag](https://cloud.githubusercontent.com/assets/14201912/17593962/41c20734-6005-11e6-9829-98913e20e03f.PNG)
- Clicked Next and again clicked Previous -> Wizard now going back to Fragment cache screen

![frag](https://cloud.githubusercontent.com/assets/14201912/17594067/8f8d0b44-6005-11e6-938a-30974356af82.PNG)
- Cannot re-produce hence closing.

**Closed as completed by deepshirsath** 2016-08-11 15:23 UTC
Labels: type_bug, priority_normal
