### ISSUE TITLE
Support for ZFS

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1379] opened 2017-01-26 12:30 UTC
Version: Fargo RC2
POC Vorboss

While assigning the roles, I got the following errors in the workers:
```
2017-01-24 10:30:43 72200 +0000 - ov-01 - 9897/140662765754112 - lib/ensure single - 807 - INFO - Ensure single CHAINED mode - ID 1485253843_97J6a9LFyZ - Amount of jobs pending for key ovs_ensure_single_ovs.storagerouter.configure_disk: 1
2017-01-24 10:30:43 72300 +0000 - ov-01 - 9897/140662765754112 - lib/ensure single - 808 - INFO - Ensure single CHAINED mode - ID 1485253843_97J6a9LFyZ -   KWARGS: {'partition_guid': u'0c4c0abb-a930-4199-b3be-946753f5bcb8', 'roles': [u'DB', u'WRITE'], 'disk_guid': u'ac732764-0bb7-41ee-baa8-194ea31096d0', 'storagerouter_guid': 'a33be319-ff37-4a60-9ee3-6dc4f370adce', 'offset': 1048576, 'size': 512100401152}
2017-01-24 10:30:43 75500 +0000 - ov-01 - 9897/140662765754112 - lib/storagerouter - 809 - DEBUG - Using existing partition
2017-01-24 10:30:43 75600 +0000 - ov-01 - 9897/140662765754112 - lib/storagerouter - 810 - DEBUG - Configuring mountpoint
2017-01-24 10:30:48 03800 +0000 - ov-01 - 9897/140662765754112 - lib/storagerouter - 811 - DEBUG - Found mountpoint: /mnt/ssd2
2017-01-24 10:30:48 12700 +0000 - ov-01 - 9897/140662765754112 - lib/ensure single - 812 - ERROR - Ensure single CHAINED mode - ID 1485253843_97J6a9LFyZ - Task ovs.storagerouter.configure_disk with params {'partition_guid': u'0c4c0abb-a930-4199-b3be-946753f5bcb8', 'roles': [u'DB', u'WRITE'], 'disk_guid': u'ac732764-0bb7-41ee-baa8-194ea31096d0', 'storagerouter_guid': 'a33be319-ff37-4a60-9ee3-6dc4f370adce', 'offset': 1048576, 'size': 512100401152} failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1419, in configure_disk
    rem.DiskTools.mount(mountpoint)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
CalledProcessError: Command 'mount '/mnt/ssd2'' returned non-zero exit status 32
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/tmp/tmp.PUZbca6Y60/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/tmp/tmp.PUZbca6Y60/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/opt/OpenvStorage/ovs/extensions/generic/disk.py", line 170, in mount
    check_output("mount '{0}'".format(mountpoint), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'mount '/mnt/ssd2'' returned non-zero exit status 32
2017-01-24 10:30:48 13100 +0000 - ov-01 - 9897/140662765754112 - lib/ensure single - 813 - INFO - Ensure single CHAINED mode - ID 1485253843_97J6a9LFyZ - Amount of jobs pending for key ovs_ensure_single_ovs.storagerouter.configure_disk: 0
2017-01-24 10:30:48 24400 +0000 - ov-01 - 9740/140662765754112 - celery/celery.worker.job - 22598 - ERROR - Task ovs.storagerouter.configure_disk[7fca79d8-b016-4a15-94a9-c51923d3e8b3] raised unexpected: CalledProcessError()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1419, in configure_disk
    rem.DiskTools.mount(mountpoint)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
Exception
```

This was caused due to the ZFS filesystem on the disks: 
```
[root@ov-01:~]$ lsblk 
NAME               MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                  8:0    0 279.4G  0 disk  
├─sda1               8:1    0  18.6G  0 part  
│ └─md0              9:0    0  18.6G  0 raid1 /boot
└─sda2               8:2    0 260.8G  0 part  
  └─md1              9:1    0 260.7G  0 raid1 
    ├─3nkn5y1-root 252:0    0  18.6G  0 lvm   /
    └─3nkn5y1-swap 252:1    0   3.7G  0 lvm   [SWAP]
sdb                  8:16   0 279.4G  0 disk  
├─sdb1               8:17   0  18.6G  0 part  
│ └─md0              9:0    0  18.6G  0 raid1 /boot
└─sdb2               8:18   0 260.8G  0 part  
  └─md1              9:1    0 260.7G  0 raid1 
    ├─3nkn5y1-root 252:0    0  18.6G  0 lvm   /
    └─3nkn5y1-swap 252:1    0   3.7G  0 lvm   [SWAP]


[root@ov-01:~]$ df -h
Filesystem                Size  Used Avail Use% Mounted on
udev                       16G     0   16G   0% /dev
tmpfs                     3.2G  1.4M  3.2G   1% /run
/dev/mapper/3nkn5y1-root   19G  4.6G   13G  27% /
tmpfs                      16G   12K   16G   1% /dev/shm
tmpfs                     5.0M     0  5.0M   0% /run/lock
tmpfs                      16G     0   16G   0% /sys/fs/cgroup
/dev/md0                   19G  144M   18G   1% /boot
cgmfs                     100K     0  100K   0% /run/cgmanager/fs
tmpfs                     3.2G     0  3.2G   0% /run/user/0
tmpfs                     3.2G     0  3.2G   0% /run/user/1000


[root@ov-01:~]$ cat /proc/mdstat 
Personalities : [raid1] [linear] [multipath] [raid0] [raid6] [raid5] [raid4] [raid10] 
md0 : active raid1 sda1[0] sdb1[1]
      19514240 blocks super 1.2 [2/2] [UU]
      
md1 : active raid1 sda2[0] sdb2[1]
      273305408 blocks super 1.2 [2/2] [UU]
```

Had to remove the partitions first.

**Comment by khenderick** [comment] 2017-01-27 08:28
@matthiasdeblock, where do you see the ZFS information? Can you execute `zpool status` to see the zpool's layout?

**Comment by matthiasdeblock** [comment] 2017-01-27 09:34
@khenderick all the disks got wiped... 

Also, it looks like I forgot to paste some more info:
```
Disk /dev/sdc: 1.8 TiB, 2000398934016 bytes, 3907029168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 095AE709-07FE-6142-B96B-8E9D9992A331

Device          Start        End    Sectors  Size Type
/dev/sdc1        2048 3907012607 3907010560  1.8T Solaris /usr & Apple ZFS
/dev/sdc9  3907012608 3907028991      16384    8M Solaris reserved 1
```

Output you asked for was negative. Module was not loaded.
```
zpool status
The ZFS modules are not loaded.
Try running '/sbin/modprobe zfs' as root to load them.
```

Alba did not had any issues to claim the disks. Only assigning the roles did not work.

**Comment by khenderick** [comment] 2017-01-27 09:44
If the zfs modules are not loaded, are you sure it was actually ZFS that was the cause of the issue, or just the lvm-on-top-of-md that we don't support (correctly)?

**Comment by matthiasdeblock** [comment] 2017-01-27 10:38
I'm sure it was this:
```
Device          Start        End    Sectors  Size Type
/dev/sdc1        2048 3907012607 3907010560  1.8T Solaris /usr & Apple ZFS
/dev/sdc9  3907012608 3907028991      16384    8M Solaris reserved 1
```

After removing the partitions it worked without any issue.

**Comment by khenderick** [comment] 2017-01-30 10:50
Odd that `/dev/sdc` wasn't in the `lsblk`.

**Comment by matthiasdeblock** [comment] 2017-01-30 14:34
Not sure what happened when pasting in GH but it was... 

Output from another node that had the same configuration but is not part of the OVS cluster:
```
[root@ov-04:~]$ lsblk 
NAME               MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                  8:0    0 279.4G  0 disk  
├─sda1               8:1    0   1.9G  0 part  
│ └─md0              9:0    0   1.9G  0 raid1 /boot
└─sda2               8:2    0 277.5G  0 part  
  └─md1              9:1    0 277.4G  0 raid1 
    ├─68dsd5j-root 252:0    0  18.6G  0 lvm   /                                                                                                                                                                                                                                
    └─68dsd5j-swap 252:1    0   3.7G  0 lvm   [SWAP]                                                                                                                                                                                                                           
sdb                  8:16   0 279.4G  0 disk                                                                                                                                                                                                                                   
├─sdb1               8:17   0   1.9G  0 part                                                                                                                                                                                                                                   
│ └─md0              9:0    0   1.9G  0 raid1 /boot                                                                                                                                                                                                                            
└─sdb2               8:18   0 277.5G  0 part                                                                                                                                                                                                                                   
  └─md1              9:1    0 277.4G  0 raid1                                                                                                                                                                                                                                  
    ├─68dsd5j-root 252:0    0  18.6G  0 lvm   /                                                                                                                                                                                                                                
    └─68dsd5j-swap 252:1    0   3.7G  0 lvm   [SWAP]                                                                                                                                                                                                                           
sdc                  8:32   0   1.8T  0 disk                                                                                                                                                                                                                                   
├─sdc1               8:33   0   1.8T  0 part                                                                                                                                                                                                                                   
└─sdc9               8:41   0     8M  0 part                                                                                                                                                                                                                                   
sdd                  8:48   0   1.8T  0 disk                                                                                                                                                                                                                                   
├─sdd1               8:49   0   1.8T  0 part                                                                                                                                                                                                                                   
└─sdd9               8:57   0     8M  0 part                                                                                                                                                                                                                                   
sde                  8:64   0   1.8T  0 disk                                                                                                                                                                                                                                   
├─sde1               8:65   0   1.8T  0 part                                                                                                                                                                                                                                   
└─sde9               8:73   0     8M  0 part                                                                                                                                                                                                                                   
sdf                  8:80   0   1.8T  0 disk                                                                                                                                                                                                                                   
├─sdf1               8:81   0   1.8T  0 part                                                                                                                                                                                                                                   
└─sdf9               8:89   0     8M  0 part                                                                                                                                                                                                                                   
sdg                  8:96   0   1.8T  0 disk                                                                                                                                                                                                                                   
├─sdg1               8:97   0   1.8T  0 part                                                                                                                                                                                                                                   
└─sdg9               8:105  0     8M  0 part                                                                                                                                                                                                                                   
sdh                  8:112  0   477G  0 disk  
├─sdh1               8:113  0   477G  0 part  
└─sdh9               8:121  0     8M  0 part  
sdi                  8:128  0   477G  0 disk  
├─sdi1               8:129  0   477G  0 part  
└─sdi9               8:137  0     8M  0 part  
sdj                  8:144  0   1.8T  0 disk  
├─sdj1               8:145  0   1.8T  0 part  
└─sdj9               8:153  0     8M  0 part  
sdk                  8:160  0   1.8T  0 disk  
├─sdk1               8:161  0   1.8T  0 part  
└─sdk9               8:169  0     8M  0 part  
sdl                  8:176  0   1.8T  0 disk  
├─sdl1               8:177  0   1.8T  0 part  
└─sdl9               8:185  0     8M  0 part  
```

**Comment by bazzspeed** [comment] 2017-02-16 13:40
I've also had some problems around ZFS. Attempting to add roles to a partition fails.
I ended up using `wipefs -a [partition]` to remove all traces of ZFS and then it worked; created partition and added roles all good.

The issue might just be related to the way that a mount point is setup with a zpool, as they're automounted with some zpool parameter I think ?

**Comment by wimpers** [comment] 2017-10-19 07:55
There are no plans for ZFS support in the backend so closing this one down. If we get the request we can re-open or create a new ticket.

**Closed as completed** 2017-10-19 10:30 UTC
Labels: process_wontfix, priority_normal, type_enhancement
