### ISSUE TITLE
Rescan not possible if a volumedriver disk is broken

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#897] opened 2016-09-13 14:41 UTC
When losing a write role and trying to replace it we get this problem: 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/disk.py", line 212, in sync_with_reality
    partition.delete()
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 700, in delete
    raise LinkedObjectException('There {0} left in self.{1}'.format(multi, key))
LinkedObjectException: There are 4 items left in self.storagedrivers
```

**Comment by kinvaris** [comment] 2016-09-13 14:44
This happens when a disk goes down but and the volumedriver fails to steal the volumes because the 'broken' node is still online

**Comment by wimpers** [comment] 2016-09-14 07:42
Duplicate of https://github.com/openvstorage/framework/issues/832  ?

**Closed as completed** 2016-09-14 12:52 UTC
Labels: type_bug, process_duplicate
