### ISSUE TITLE
Too much space requested for DB/WRITE cache

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#615] opened 2016-06-15 11:07 UTC
When creating a vpool i got following errors:

The available Write cache and the requested cache are the same (why do we get an error for this?):

```
Task ovs.storagerouter.add_vpool[c74ee0c4-3ce6-494c-a80f-8b2222a64f2f] raised unexpected: ValueError('Errors validating the partition roles:\n - Too much space requested for WRITE cache. Available: 46.00 GiB, Requested: 46.00 GiB',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 541, in add_vpool
    raise ValueError('Errors validating the partition roles:\n - {0}'.format('\n - '.join(set(error_messages))))
ValueError: Errors validating the partition roles:
 - Too much space requested for WRITE cache. Available: 46.00 GiB, Requested: 46.00 GiB
```

The DB available space and the requested space are the same (why do we get an error for this?):

```
Task ovs.storagerouter.add_vpool[fa83ae50-51ff-43c8-b7d5-671e0d4d0069] raised unexpected: ValueError('Errors validating the partition roles:\n - Too much space requested. Available: 132.00 GiB, Requested: 132.00 GiB\n - Too much space requested for WRITE cache. Available: 45.16 GiB, Requested: 46.00 GiB',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 541, in add_vpool
    raise ValueError('Errors validating the partition roles:\n - {0}'.format('\n - '.join(set(error_messages))))
ValueError: Errors validating the partition roles:
 - Too much space requested. Available: 132.00 GiB, Requested: 132.00 GiB
 - Too much space requested for WRITE cache. Available: 45.16 GiB, Requested: 46.00 GiB
```

**Comment by matthiasdeblock** [comment] 2016-06-16 15:56
Having the same issue:

```
2016-06-16 17:54:37 70500 +0200 - ovs01 - 61680/139910093670208 - celery/celery.worker.job - 20013 - ERROR - Task ovs.storagerouter.add_vpool[2ff240b6-390b-4f02-b9a2-168e0f15ce05] raised unexpected: ValueError('Errors validating the partition roles:\n - Too much space requested. Available: 160.12 GiB, Requested: 167.00 GiB\n - Too much space requested for WRITE cache. Available: 55.87 GiB, Requested: 63.00 GiB',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 541, in add_vpool
    raise ValueError('Errors validating the partition roles:\n - {0}'.format('\n - '.join(set(error_messages))))
ValueError: Errors validating the partition roles:
 - Too much space requested. Available: 160.12 GiB, Requested: 167.00 GiB
 - Too much space requested for WRITE cache. Available: 55.87 GiB, Requested: 63.00 GiB
```

**Comment by kvanhijf** [comment] 2016-07-14 12:10
Calculation done in the GUI was identical to calculation in controllers, but issue was introduced when the 'enhancedPresets' functionality in the GUI was removed
Re-introduced this, thus fixing this issue

**Comment by kinvaris** [comment] 2016-08-16 15:18
PASSED: duplicate of https://github.com/openvstorage/framework/issues/592

**Closed as completed by kinvaris** 2016-08-16 15:18 UTC
Labels: type_bug, priority_critical
