### ISSUE TITLE
bad sco cache (global write buffer) configuration

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/framework#1484] opened 2017-02-27 09:03 UTC
On tenv186...
```
[09:54:40] Arne Redlich: the thing is that 2 sco cache mountpoints are configured:
[09:54:41] Arne Redlich: "scocache_mount_points": [
            {
                "path": "/mnt/ssd2/hapool_write_sco_1", 
                "size": "46080000KiB"
            }, 
            {
                "path": "/mnt/ssd1/hapool_write_sco_1", 
                "size": "57344KiB"
            }
        ]
[09:54:57] Arne Redlich: together with these settings:
"trigger_gap": "1GB", 
        "backoff_gap": "2GB",
[09:55:39] Arne Redlich: IOW the second mountpoint is always in a bad state as it can never reach a free space of 2GB
```

Results in 
```
Feb 27 09:35:00 ftcmp02 volumedriver_fs.sh[3766]: 2017-02-27 09:35:00 441189 +0100 - ftcmp02 - 3766/0x00007fa1b2b31700 - volumedriverfs/SCOCache - 00000000000f9ade - info - trimMountPoint_: "/mnt/ssd1/hapool_write_sco_1" is choking: free 56MiB < trigger 953MiB. Throttling ingest with 68119 usec per cluster write.
```

There's a related voldrvr ticket (https://github.com/openvstorage/volumedriver/issues/228) for the voldrvr not accepting such a config but the creating a bad config shouldn't be possible either... 

Global Write Buffer was set to 50 GiB via the GUI.

**Comment by dejonghb** [comment] 2017-02-27 09:07
```
# du -sh /mnt/ssd1/hapool_write_sco_1/
40K	/mnt/ssd1/hapool_write_sco_1/
```
```
Filesystem                            Size  Used Avail Use% Mounted on
 /dev/sde1                             275G  223M  261G   1% /mnt/ssd1
```

**Comment by khenderick** [comment] 2017-02-28 10:21
I think this one more or less duplicates #1332

**Comment by wimpers** [comment] 2017-02-28 10:50
Closed as duplicate. Re-open if needed.

**Comment by dejonghb** [comment] 2017-02-28 13:33
Please also check the configured sizes as
```
            {
                "path": "/mnt/ssd1/hapool_write_sco_1", 
                "size": "57344KiB"
            }
```
is only 56 MiB what looks rather small to me... It's not that there's no room left on ssd1 (cfr the df above)

**Comment by kvanhijf** [comment] 2017-03-01 08:56
The related issue (https://github.com/openvstorage/framework/issues/1332) has been fixed and it should no longer be possible to run into this issue. Since we now calculate the backoff_gap based on the smallest WRITE partition, which would have been 56MiB in this case
However the fact that 1 SCO cache's size is 56MiB and the other is +/- 50GiB, this issue is not yet fixed

Question is, should this be fixed?

Reason for this behavior is the following:
Eg: 2 WRITE roles have been defined
Partition 1 with WRITE role is 1GiB
Partition 2 with WRITE role is 99GiB
Customer can choose up to 100GiB for global write buffer 
If he chooses to use 50GiB, then we do the following
Partition 1 is 1% of total available space ==> 1 % of requested size is assigned to partition 1, being 0.5GiB
Partition 2 is 99% of total available space ==> 99% of requested size is assigned to partition 2, being 49.5GiB

**Comment by kvanhijf** [comment] 2017-03-01 09:24
Spoke with @dejonghb about how this issue was detected
1 partition with WRITE role of +/- 260GiB
Created vPool claiming all available space for the global write buffer --> couple of MiBs left
He could not create additional vPools since we require a minimum of 1GiB for the global write buffer.
He added another WRITE role to another disk (+/- 450GiB)
When creating the next vPool, the framework code will use all partitions for the write buffer, which shouldn't be done since the 1st partition had less than 1GiB available space

**Comment by dejonghb** [comment] 2017-03-03 14:53
> When creating the next vPool, the framework code will use all partitions for the write buffer, **which shouldn't be done** since the 1st partition had less than 1GiB available space

**Comment by wimpers** [comment] 2017-03-08 17:10
Bam assumes it is a small one. revert if not

**Comment by khenderick** [comment] 2017-03-09 08:30
No, it's not.

**Comment by wimpers** [comment] 2017-03-09 08:49
@dejonghb what happens in the below scenario

> When creating the next vPool, the framework code will use all partitions for the write buffer, **which shouldn't be done** since the 1st partition had less than 1GiB available space

does the vPool creation work or does it fail if it selects that partition smaller than 1GB?

**Comment by kvanhijf** [comment] 2017-03-09 09:05
@wimpers : question not addressed to me, but answering anyway.
The vPool creation will work, however there will be 2 SCO caches (1 with a very small size and 1 with an expected size) resulting in a very small backoff gap (because based on smallest SCO cache), thus perhaps introducing unexpected behavior

**Comment by wimpers** [comment] 2017-03-09 09:09
Wild idea: Claim small left over amount when creating the vpool so we don't end up in a scenario where you have less than 1GB left as partition.

since it doesn't fail, not that urgent to fix for RC4

**Comment by dejonghb** [comment] 2017-03-09 10:11
Fine as long as the throttling ingest and choking isn't a performance stopper?

```
Feb 27 09:35:00 ftcmp02 volumedriver_fs.sh[3766]: 2017-02-27 09:35:00 441189 +0100 - ftcmp02 - 3766/0x00007fa1b2b31700 - volumedriverfs/SCOCache - 00000000000f9ade - info - trimMountPoint_: "/mnt/ssd1/hapool_write_sco_1" is choking: free 56MiB < trigger 953MiB. Throttling ingest with 68119 usec per cluster write.
```

**Comment by kvanhijf** [comment] 2017-04-03 15:43
@openvstorage/qa : 
Partitions with WRITE role will be excluded if:
* Available space is < 1 GiB
* Available space < 5% of largest WRITE partition

Examples:
* Example1:
  * Partition 1: 100 GiB
  * Partition 2: 50 GiB
  * Partition 3: 500 MiB
  * Partitions 1 and 2 will be used for SCO caches, partition 3 is not used because smaller than 1 GiB
* Example 2:
  * Partition 1: 500 GiB
  * Partition 2: 20 GiB
  * Only partition 1 will be used since partition 2 is smaller than 5% of partition 1

https://github.com/openvstorage/framework/pull/1572 --> openvstorage-2.8.2-dev.1491233108.9d61930

**Closed as completed** 2017-08-10 08:08 UTC
Labels: priority_critical, type_enhancement
