### ISSUE TITLE
global backend shows asds of local backend as available but they cannot be claimed

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1284] opened 2016-12-20 09:32 UTC
cosmetic error:
global backend:
![screen shot 2016-12-19 at 09 48 23](https://cloud.githubusercontent.com/assets/8393135/21345200/7fad5804-c69f-11e6-9f60-56c585008172.png)

local backend - where asds are claimed:
![screen shot 2016-12-19 at 09 57 19](https://cloud.githubusercontent.com/assets/8393135/21345210/8d11921c-c69f-11e6-8b24-e5c2672a89ba.png)

**Comment by khenderick** [comment] 2017-01-20 15:53
I can't reproduce this.

@pploegaert, can you give more information on what exactly was going on, or steps on how to reproduce this?

**Comment by wimpers** [comment] 2017-02-03 13:33
Back to BAM as @pploegaert is on holiday and this ticket is part of RC4.

**Comment by wimpers** [comment] 2017-06-07 09:24
@pploegaert  @JeffreyDevloo  please let us know if you can reproduce, otherwise best to close it down. Maybe verify on Nuvolat?

**Comment by wimpers** [comment] 2017-09-13 09:21
Since Philippe is no longer with us, assigning to @JeffreyDevloo

**Comment by JeffreyDevloo** [comment] 2017-09-13 11:46
I find it odd that a global backend could claim asds or that a local backend would be marked as global. Either something is wrong with the description or picture?
Either way, I'm closing this issue down as neither cases could be reproduced

**Closed as completed by JeffreyDevloo** 2017-09-13 11:46 UTC
Labels: type_bug, priority_normal, process_cantreproduce
