### ISSUE TITLE
Removing a non-available ASD failed

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1591] opened 2017-04-19 15:52 UTC
While removing a disk on OVH environment I received the following error message:
```
[14:48:41] Matthias De Block: Apr 19 14:33:54 ovs01 celery[184887]: 2017-04-19 14:33:54 64400 +0200 - ovs01 - 184887/140061285873408 - celery/celery.worker.job - 1376 - ERROR - Task albanode.remove_disk[e05349b8-39aa-46c1-bbb6-140117525e36] raised unexpect
Apr 19 14:33:54 ovs01 celery[184887]: Traceback (most recent call last):
Apr 19 14:33:54 ovs01 celery[184887]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Apr 19 14:33:54 ovs01 celery[184887]:     R = retval = fun(*args, **kwargs)
Apr 19 14:33:54 ovs01 celery[184887]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Apr 19 14:33:54 ovs01 celery[184887]:     return self.run(*args, **kwargs)
Apr 19 14:33:54 ovs01 celery[184887]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 454, in new_function
Apr 19 14:33:54 ovs01 celery[184887]:     output = function(*args, **kwargs)
Apr 19 14:33:54 ovs01 celery[184887]:   File "/opt/OpenvStorage/ovs/lib/albanode.py", line 217, in remove_disk
Apr 19 14:33:54 ovs01 celery[184887]:     raise RuntimeError('Disk {0} on ALBA node {1} has still some non-available ASDs'.format(device_alias, node_id))
Apr 19 14:33:54 ovs01 celery[184887]: RuntimeError: Disk /dev/disk/by-id/nvme-INTEL_SSDPEDMD016T4_CVFT6160008Y1P6DGN on ALBA node  FxXoqkiEYxQwHQ4arF2mhgA905in7TWv has still some non-available ASDs
```

On both NVME nodes I've ran the nvmebackend maintenancer to initialize the disk but while running the nvmebackend maintenancer, the disk couldn't get removed (see the above error). 

After some research it looked like all the maintenancers had to be started before I could remove the disks.

**Comment by kvanhijf** [comment] 2017-04-20 07:12
Question is actually, do we need to block on this?  Can we assume the disk can safely be removed even though not all disks are marked as 'available'?

**Comment by khenderick** [comment] 2017-04-20 12:04
This is a safeguard against deleting ASDs that might belong to another backend, so I'd rather keep that in place. And at this point, we query alba for information about that ASD, so we can see whether it's available or not. We can always remove safety checks, but it will obviously less safe then.

@wimpers, @saelbrec, can you make a decision here?

**Comment by khenderick** [comment] 2017-04-20 12:05
Removing the `type_bug` label as it's not a bug but a designed safety feature.

**Comment by domsj** [comment] 2017-04-20 12:19
I don't see how assuming the asd might belong to another backend when that backend explicitly tells you it doesn't know about this particular asd adds any safety?

**Comment by khenderick** [comment] 2017-04-20 12:21
If we notice there are ASDs on a disk, and we can't figure out whether they belong to some backend, we don't want to wipe that disk.

**Comment by khenderick** [comment] 2017-04-20 12:27
Let's keep this as a `type_enhancement`. Since alba 1.3.7 we can ask the ASD directly. Then we don't rely on the maintenance processes for this safety feature.

**Closed as completed** 2017-04-24 14:57 UTC
Labels: type_enhancement, process_moved
