### ISSUE TITLE
Scrub enhancements

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#1559] opened 2017-03-27 16:48 UTC
- [x] Allow and correctly handle scrubbing multiple vdisks(of the same or different vpool) on the same storagerouter simultaneously. Code inspection revealed that we need to further investigate and fix potential issue in the proxy cleanup section of scrub job where the first one upon completion kills the proxy for all other remaining instances.

Depending on the work involved, we can do following items now or later
- [x] API to take as param a list of vdisks
- [x] Make the maximum number of allowed scrub jobs configurable on a per node base.

**Comment by khenderick** [comment] 2017-03-29 10:33
At this point, all disks to be scrubbed are put in a queue. A number of "stacks" are created (a "stack" being a combination of vPool/StorageRouter) and they are processing this same queue simultaneously. Every stack sets up its Proxy and removes it once the queue is empty. The issue is that if a given stack is executed multiple times, they will conflict each other.

What look to me like the safe options:
* Add threads within a "stack" so a single "stack" can process multiple disks at the same time (with the same Proxy)
* Block the same "stack" to be executed multiple times
* Add an API that can scrub a list of vDisks of a given vPool.

Implications:
* Calling the single-disk-scrub API multiple times will cause them to be executed one-by-one
* Calling the multiple-disk-scrub API will allow usage of the parallel scrubbing.

**Comment by wimpers** [comment] 2017-03-30 08:51
@khenderick will this be part of RC4?

**Comment by khenderick** [comment] 2017-03-30 08:53
No, it will be part of Gilbert 2.8.1.

**Comment by kvanhijf** [comment] 2017-03-31 13:59
openvstorage-2.8.1-dev.1490966663.561c40e

@openvstorage/qa : 
New API call on vPools: scrub_multiple_vdisks. Takes a list of vdisk_guids as parameter and the vpool they belong to. This allows a user to scrub multiple vdisks simultaneously.

Also the amount of simultaneous scrub jobs per SCRUB partition can now be configured (default 2)
This could proof useful for dedicated SCRUB nodes
To configure it, do the following:
`Configuration.set(key='/ovs/framework/hosts/<machine_id>/config|scrub_stack_threads', value=5)`

Values between 1 and 20 are enforced, so anything falling out of that range will be overruled internally

# How scrubbing distribution works:

- Collect StorageRouters with SCRUB role
- Make buckets with vDisks per vPool (Queues)
- Launch calculated amount of threads to do the scrubbing on the different StorageRouters, each thread will do:
  - Spawn a scrub proxy
  - Deploy several other threads (configurable, but 2 is default), to execute the actual scrubbing
    - These threads are responsible for emptying the buckets
  - Delete the scrub proxy

# Nice to know

Every scrubbing request will cause a separate scrub proxy to be created
Scrubbing requests can come from:
- Scheduled task
- API to scrub single vDisk
- API to scrub multiple vDisks

If a vDisk is being scrubbed (eg requested via API) and a scheduled task starts scrubbing, the vDisks being scrubbed, will be skipped

**Comment by khenderick** [comment] 2017-04-03 12:01
openvstorage-2.8.1

**Closed as completed** 2017-08-10 08:14 UTC
Labels: type_enhancement
