### ISSUE TITLE
browser cache not cleaned after entering the remote hosts credentials (linked backends)

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1636] opened 2017-05-10 10:05 UTC
When i link a remote backend and fill in the form the next time the backends are shown as local backends.

remote backends:
![link_remote_backend](https://cloud.githubusercontent.com/assets/2900612/25893569/9d8851ba-3578-11e7-9cb7-4ac0af812346.png)

Canceled the form and try to link a backend again.
![link_local_backend](https://cloud.githubusercontent.com/assets/2900612/25893608/bd8ca3a8-3578-11e7-9947-bcaf7dffe16d.png)

**Comment by wimpers** [comment] 2017-05-29 13:58
@khenderick BAM aasumes it is a small fix. revert if not.

**Comment by khenderick** [comment] 2017-06-13 12:40
I could not reproduce this. However, I noticed a bit of a delay (about a second) in which the previous values were showed.

**Comment by khenderick** [comment] 2017-06-13 12:42
It might be possible that some race condition would somehow intervene in the reloading process, leaving the old information in place, so let's consider this a bug anyway.

**Comment by khenderick** [comment] 2017-06-13 12:59
Fixed by openvstorage/framework-alba-plugin#425, packaged in openvstorage-backend-1.9.2-dev.1497358569.ba4e853

**Comment by JeffreyDevloo** [comment] 2017-07-11 14:42
Packaged in openvstorage-backend_1.9.2-1_amd64.deb

**Closed as completed** 2017-08-10 08:13 UTC
Labels: type_bug
