### ISSUE TITLE
redundant docker cluster for framework on ubuntu 16.04

### ISSUE THREAD

**Issue by despiegk** [openvstorage/framework#518] opened 2016-04-25 12:00 UTC
inside components
- etcd
- rabbitmq
- memcache

outside components are
- arakoon
- alba
- vol driver
- ...

use weave to connect the dockers
- create procedure how to build it & install it
- and connecting the 3 dockers to each other over weave

**Comment by delandtj** [comment] 2016-05-31 09:55
Hmmm.. I figure with all our networking in place to properly connect dockers over an openvswitch bridge, I would omit the weave part and connect the dockers to backplane1 , so that all the difficulties of ip assignments for etcd, arakoon... would simply vanish.

Also, I dont know what the repercussions might be of a weave setup running on an already set-up openvswitch env like we have in place. Weave shoots flows directly in the openvswitch kernel module, and that might wreak havoc in our ovsdb (I suppose, haven't tested that).

**Only caveat: it will be included in docker-1.12**, for now do: 
(after stopping docker of course)
`wget  https://experimental.docker.com/builds/Linux/x86_64/docker-latest -O $(which docker)`
(and starting docker, of course)

```
# create an interface for the framework VM (to properly separate), evenually with a vlan tag
ovs-vsctl add-port backplane1 framework [tag=XXX] -- set Interface framework type=internal
# make sure the interface is up
ip l set framework up
# create a MACVLAN network in the segment/subnet where you want it
docker network create -d macvlan --subnet=backplane1subnet/cidr --gateway=bkplndeftgw  -o partent=framework framework
#run the docker on the network
docker run --net=framework --rm -it --name=framework1 --ip=ipinbackplane1 alpine /bin/sh
# and in VM:
ping ipofCPU01
```

this way, the framework VM (an UberDocker) sits directly in the network where all the stuff happens, without the need for DNAT/SNAT and/or cumbersome routing issues

**NOTE:** by design, if you want to use a MACVLAN directly on an interface (say: eth0, enp3s0,...) the linux kernel filters out direct communication to the IP addr of the parent interface. This works here, because we have defined a NEW interface on the openvswitch bridge (without an ip address) and as such, the filtering has no effect.

Reference : [Docker experimental MACVLAN](https://github.com/docker/docker/blob/master/experimental/vlan-networks.md)

**Comment by wimpers** [comment] 2016-06-20 15:02
@dejonghb what is the status of this ticket?

**Comment by dejonghb** [comment] 2016-06-20 15:17
https://github.com/openvstorage/docker-tools/tree/master/framework had a working setup but meanwhile development moved along and this got probably outdated faster that I can type. 

The framework is dockerised, but documentation on external components and the interactions between the framework inside the container to/from those external components is very scarce to non-existing and ever changing without notice.

For the MACVLAN mentioned above: docker 1.12.0 appears to be targeted for 2016-07-14; rc2 got released 3 days ago (cfr. https://github.com/docker/docker/releases) with MACVLAN now out of experimental.

**Comment by wimpers** [comment] 2016-06-28 13:19
Awaiting input of @saelbrec

**Comment by wimpers** [comment] 2018-08-27 15:29
As Stefaan is no longer here, no input will be given.
Please re-open if needed.

**Closed as completed by wimpers** 2018-08-27 15:29 UTC
Labels: type_feature, process_wontfix
